# Problem 2 - Even Fibonacci numbers
"""
	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose 
	values do not exceed four million, find the sum of the even-valued terms.

IMPROVED SOLUTION:
	not using an array

"""

root = 0
prev = 1
cur = 0
total = 0

limit = 4000000

while cur < limit:
	cur = root + prev
	root = prev
	prev = cur
	if cur % 2 == 0: total += cur


print("The sum of all EVEN Fibonacci numbers below " + str(limit) + " is: " + str(total))