# Problem 2 - Even Fibonacci numbers
"""
	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose 
	values do not exceed four million, find the sum of the even-valued terms.

1. Write code for Fibonacci sequence
2. Put upper loop boundary on 4. million
3. Sum even numbers

"""

current = 1
total = 0
limit = 4000000
i = 0

fibzz = [1, 1]

while current < limit:

	current = fibzz[i]
	print(str(i) + " : " + str(fibzz[i]))
	fibzz.append(fibzz[i]+fibzz[i+1])
	i += 1

	if fibzz[i-1]%2 == 0:
		total += fibzz[i-1]

print("The sum of all EVEN Fibonacci numbers below " + str(limit) + " is: " + str(total))